# Generated by Django 5.1.7 on 2025-03-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.TextField(blank=True, null=True, unique=True)),
                ('error_count', models.IntegerField(default=0)),
                ('recipients', models.JSONField(blank=True, null=True)),
                ('report_text', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_chars', models.TextField(blank=True, null=True)),
                ('file_time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_log',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('is_reference', models.BooleanField(blank=True, db_index=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paragraphs',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'docx_usertoken',
            },
        ),
    ]
